# Path: config/model.yaml
grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
    n_jobs: -1
    
model_selection:
  module_0:
    class: XGBRegressor
    module: xgboost
    params:
      max_depth: 7
      min_child_weight: 1
    search_param_grid:
      max_depth:
      - 3
      - 5
      - 7
      - 9
      min_child_weight:
      - 1
      - 2
      - 3
      - 5

      
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      max_depth: 20
      max_features: sqrt
      n_estimators: 100
    search_param_grid:
      max_depth:
      - 10
      - 15
      - 20
      max_features:
      - sqrt
      - log2
      n_estimators:
      - 3
      - 5
      - 9